name: FTP Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.yolostudio.in
          username: kumarkalyan736@yolostudio.in
          password: ${{ secrets.FTP_PASSWORD }}
